name: core_dev_debug
description: Push notification debug logging for development builds.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.11.5
  flutter: '>=3.41.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  awesome_notifications: ^0.11.0
  awesome_notifications_fcm: ^0.11.0
  hive_ce: ^2.19.3

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
